export const FETCH_TOP_HEADLINES_REQUEST = "FETCH_TOP_HEADLINES_REQUEST";
export const FETCH_TOP_HEADLINES_SUCCESS = "FETCH_TOP_HEADLINES_SUCCESS";
export const FETCH_TOP_HEADLINES_FAILURE = "FETCH_TOP_HEADLINES_FAILURE";
