export const FETCH_SEARCH_NEWS_REQUEST = "FETCH_SEARCH_NEWS_REQUEST";
export const FETCH_SEARCH_NEWS_SUCCESS = "FETCH_SEARCH_NEWS_SUCCESS";
export const FETCH_SEARCH_NEWS_FAILURE = "FETCH_SEARCH_NEWS_FAILURE";
